### PR TITLE
Bloom shader

### PR DESCRIPTION
**Pull request by camchenry**
I thought shine could use a bloom shader so I adapted a shader to use for love2d and edited it to match the format of other shaders.

### CODE REVIEW

**Comment by vrld** [comment]
This looks like a simple box blur shader (which is [already included](https://github.com/vrld/shine/blob/master/boxblur.lua)). A [glow shader](https://github.com/vrld/shine/blob/master/glowsimple.lua) is also included. Am I missing something?

**Comment by camchenry** [comment]
You're right, I did not inspect the boxblur and glow code in depth. After some tweaking, I was able to get something that replicated the effect I wanted. The only weird thing is that it didn't work unless I used both boxblur and glow, even though boxblur radius was set to 0. Does the boxblur still have an effect in that case?

**Comment by vrld** [comment]
With radius 0, boxblur will become the passthrough shader:

```
vec4 effect(vec4 color, Image texture, vec2 tc, vec2 _) {
    return Texel(texture, tc + i * direction) * color;
}
```

What kind of effect are you looking for? Can you provide a screenshot?

**Comment by vrld** [comment]
Closing, because the shader is already included.

**Pull request closed without merging**
