### PR TITLE
Make shaders work on Android/iOS

### PR DESCRIPTION
**Pull request by pablomayobre**
Made some changes to the shaders that shouldnt brake them in Windows/Linux/MacOSX but that would allow them to run in Android/iOS devices. They are not tested, neither in PC nor in Mobile devices, tests should be made before merging, but since I cant do it I'll put it here so someone can try them out

PS: Sorry for the quantity of commits, I modified the files online, one by one

### CODE REVIEW

**Comment by vrld** [comment]
Awesome, thanks!

**Comment by pablomayobre** [comment]
Did they work? Awesome I had no faith in them, I have never worked with shaders actually (since my PC doesnt support them) but I have knowledge on them (investigated when shaders didnt work in Android). Glad you liked it.

If you want to support Android devices in future shaders check [this page](https://bitbucket.org/MartinFelis/love-android-sdl2/wiki/Shaders_in_Android) in the wiki of Love Android, it has most of the errors that you can find when trying to run a shader made for OpenGL in OpenGLES

**Comment by vrld** [comment]
There were some typos and you missed an error in gaussianblur, but nothing unfixable. I also tested the effects on my android phone and apart from filmgrain (also fixed now) they seem to work.

**Comment by pablomayobre** [comment]
Yoohoo! I guessed there would be some typos I re checked many times but if I'm not able to run it I'll not be sure of it hahaha.
Is there anything to add? functions that may not be available and such (round may be one of them)?

**Pull request merged**
